language: ruby
dist: trusty
rvm:
  - 2.3.1

install:
  - sudo apt-get update
  - sudo sudo apt-get -y install linux-headers-$(uname -r)
  - bundle install
  - wget http://download.virtualbox.org/virtualbox/5.1.6/virtualbox-5.1_5.1.6-110634~Ubuntu~trusty_amd64.deb -O vbox.deb
  - wget https://releases.hashicorp.com/vagrant/1.8.5/vagrant_1.8.5_x86_64.deb -O vagrant.deb
  - sudo dpkg -i vbox.deb
  - sudo dpkg -i vagrant.deb

before_script:
  - VBoxManage --version
  - vagrant --version

script:
  - bundle exec rubocop
  - |
    for rc in examples/*; do
      echo Status for $rc
      PENTESTRC=$rc vagrant status
      echo
    done
